# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master', 'workflow']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test-unit

      - name: Run Cypress tests
        run: npm run test-e2e-cli

      - name: Setup Pages
        if: ${{ success() }} # Only run if previous steps succeeded
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ success() }} # Only run if previous steps succeeded
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        if: ${{ success() }} # Only run if previous steps succeeded
        id: deployment
        uses: actions/deploy-pages@v4
